language: java
jdk:
  - openjdk17

#before_deploy:
 # - gem install specific_install || true
 # - gem specific_install https://github.com/tumblr/tumblr_client || true
 # - gem specific_install https://github.com/lostisland/faraday || true
#sudo: required

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: book-demo-store-biswajit
  on:
    branch: develop
    #all_branches: true
