language: java
jdk:
  - openjdk8

script:
  - ./gradlew check

before_deploy:
  - gem install specific_install || true
  - gem specific_install https://github.com/tumblr/tumblr_client || true
  - gem specific_install https://github.com/lostisland/faraday || true
  -
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  on:
    all_branches: true
  app: "book-demo-store-biswajit"
